[grid]
# hidden_dim = [128, 512]
hidden_dim = [128]

# num_transformer_heads = [2,4,8]
# tr_layers = [2,3,4,5]
# # dropout = [0.1, 0.15, 0.2]
# out_features = [128, 512]
# mamba_d_state         = [6,7,8]        # внутреннее состояние mamba
# mamba_ker_size        = [3,4,5,6,7]        # размер kernel
# mamba_layers = [6,7,8,9]

[defaults]
hidden_dim = 512
# mamba_d_state = 6
# mamba_layer_number = 4
# pers_loss_type = 'rmse_gl'
